"use client";

import { useEffect, type CSSProperties } from "react";
import type { Event, EventLink, LinkScores } from "@/lib/api";
import { LABELS, type LayerId } from "@/lib/layers";
import { eventColor } from "@/lib/globe-config";
import { relationLabel } from "@/components/related-event-controls";

type Props = {
  link: EventLink;
  source?: Event;
  target?: Event;
  /** Stage-relative click point; the card opens beside it, clamped inside the stage. */
  x: number;
  y: number;
  stageWidth: number;
  stageHeight: number;
  onVisit: (event: Event) => void;
  onClose: () => void;
};

const WIDTH = 320, PAD = 16, GAP = 18;
const percent = (value: number) => `${Math.round(value * 100)}%`;
const shortTime = (value: string) => {
  const date = new Date(value);
  return Number.isNaN(date.getTime()) ? "" : new Intl.DateTimeFormat("en", { month: "short", day: "numeric", hour: "2-digit", minute: "2-digit", timeZone: "UTC", hour12: false }).format(date) + " UTC";
};
// link_events.py writes "mechanism\n\nCausal chain: …\n\nEvidence: …"; label the known sections.
const SECTION = /^(Causal chain|Evidence):\s*/;

function EventButton({ event, onVisit }: { event?: Event; onVisit: (event: Event) => void }) {
  if (!event) return <p className="link-event is-missing">Event not in the loaded dataset</p>;
  return <button className="link-event" style={{ "--pin-color": eventColor(event.layerId) } as CSSProperties} onClick={() => onVisit(event)}>
    <span className="link-event-title">{event.title}</span>
    <span className="link-event-meta">{LABELS[event.layerId as LayerId] ?? event.layerId} · {event.source.toUpperCase()} · {shortTime(event.occurredAt)}</span>
  </button>;
}

/** Details for one clicked arc: the hypothesis, its reasoning, and both linked events. */
export default function LinkCard({ link, source, target, x, y, stageWidth, stageHeight, onVisit, onClose }: Props) {
  useEffect(() => {
    const close = (event: KeyboardEvent) => { if (event.key === "Escape") onClose(); };
    window.addEventListener("keydown", close);
    return () => window.removeEventListener("keydown", close);
  }, [onClose]);
  const scores = Array.isArray(link.citations) ? null : link.citations as LinkScores;
  const paragraphs = link.rationale.split(/\n\s*\n/).map(text => text.trim()).filter(Boolean);
  const left = x + GAP + WIDTH + PAD <= stageWidth ? x + GAP : Math.max(PAD, x - GAP - WIDTH);
  const top = Math.max(PAD, Math.min(y - 60, stageHeight - PAD - 120));
  return <aside className="link-card" role="dialog" aria-label={`Connection: ${relationLabel(link.relation)}`}
    style={{ left, top, width: WIDTH, maxHeight: Math.max(160, stageHeight - top - PAD) }}>
    <header className="link-card-header">
      <span className="link-relation">{relationLabel(link.relation)}</span>
      <span className="sample-badge">Hypothesis</span>
      <button className="link-close" aria-label="Close connection" onClick={onClose}>×</button>
    </header>
    <div className="link-confidence" aria-label={`Confidence ${percent(link.confidence)}`}>
      <span style={{ width: percent(link.confidence) }} />
      <strong>{percent(link.confidence)}</strong> confidence
    </div>
    <div className="link-events">
      <EventButton event={source} onVisit={onVisit} />
      <span className="link-direction" aria-hidden="true">↓</span>
      <EventButton event={target} onVisit={onVisit} />
    </div>
    {paragraphs.length > 0 && <section className="link-reasoning">
      <h4>Reasoning</h4>
      {paragraphs.map((text, index) => {
        const label = text.match(SECTION)?.[1];
        return <p key={index}>{label && <strong>{label}: </strong>}{label ? text.replace(SECTION, "") : text}</p>;
      })}
    </section>}
    {scores && (scores.plausibility !== undefined || scores.evidence !== undefined || scores.verdict) && <dl className="link-scores">
      {scores.plausibility !== undefined && <><dt>Plausibility</dt><dd>{percent(scores.plausibility)}</dd></>}
      {scores.evidence !== undefined && <><dt>Evidence</dt><dd>{percent(scores.evidence)}</dd></>}
      {scores.verdict && <><dt>Verdict</dt><dd>{scores.verdict.toLowerCase()}</dd></>}
    </dl>}
    {scores?.world_knowledge && scores.world_knowledge.length > 0 && <section className="link-reasoning">
      <h4>Background knowledge</h4>
      <ul>{scores.world_knowledge.map((item, index) => <li key={index}>{item}</li>)}</ul>
    </section>}
    {link.model && <p className="link-model">Generated by {link.model}. Unverified.</p>}
  </aside>;
}
