-- Hypothesis Globe weekend warehouse.
-- Database EVENTS, RAW VARIANT plus MART matching the shared Event / EventLink contract.
-- Warehouse is XSMALL and auto-suspends so a cold query is the remaining demo risk.

CREATE WAREHOUSE IF NOT EXISTS EVENTS_XS
  WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE
  COMMENT = 'Weekend events warehouse. Warm with SELECT 1 before the pitch.';

CREATE DATABASE IF NOT EXISTS EVENTS;
USE DATABASE EVENTS;

CREATE SCHEMA IF NOT EXISTS RAW;
CREATE SCHEMA IF NOT EXISTS MART;

USE WAREHOUSE EVENTS_XS;

CREATE TABLE IF NOT EXISTS RAW.INGEST_BATCH (
  BATCH_ID VARCHAR(64) DEFAULT UUID_STRING(),
  SOURCE VARCHAR(64) NOT NULL,
  PULLED_AT TIMESTAMP_TZ NOT NULL,
  PAYLOAD VARIANT NOT NULL
);

CREATE TABLE IF NOT EXISTS MART.EVENT (
  ID VARCHAR(256) NOT NULL,
  SOURCE VARCHAR(64) NOT NULL,
  SOURCE_URL VARCHAR(2048),
  LAYER_ID VARCHAR(64) NOT NULL,
  TITLE VARCHAR(1024) NOT NULL,
  SUMMARY VARCHAR(16777216),
  OCCURRED_AT TIMESTAMP_TZ NOT NULL,
  UPDATED_AT TIMESTAMP_TZ NOT NULL,
  LNG FLOAT NOT NULL,
  LAT FLOAT NOT NULL,
  ALT_M FLOAT,
  GEO_PRECISION VARCHAR(32) NOT NULL,
  GEO_SOURCE VARCHAR(32) NOT NULL,
  WEIGHT FLOAT NOT NULL,
  SIGNIFICANCE FLOAT NOT NULL,
  ENTITIES VARIANT NOT NULL,
  RAW_REF VARCHAR(256),
  CONSTRAINT PK_MART_EVENT PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS MART.EVENT_LINK (
  ID VARCHAR(256) NOT NULL,
  SOURCE_ID VARCHAR(256) NOT NULL,
  TARGET_ID VARCHAR(256) NOT NULL,
  RELATION VARCHAR(64) NOT NULL,
  CONFIDENCE FLOAT NOT NULL,
  RATIONALE VARCHAR(16777216) NOT NULL,
  MODEL VARCHAR(128) NOT NULL,
  CONSTRAINT PK_MART_EVENT_LINK PRIMARY KEY (ID)
);

-- API / health warmup. Safe to run on a dark warehouse; AUTO_RESUME will spin it up.
-- SELECT 1;
